# Generated by Django 3.2 on 2021-04-17 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musey', '0006_rename_song_songs_song_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratings',
            name='id',
        ),
        migrations.AddField(
            model_name='ratings',
            name='usernameSong',
            field=models.CharField(default='-1', max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='songs',
            name='artist_name',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Artists',
        ),
    ]
