# Generated by Django 3.2 on 2021-04-17 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musey', '0007_auto_20210417_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='usernameSong',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
